alamminsalo/orion

- src/main.cpp
Orion is lacking proxy support. This is basic support for system proxy settings applied to the application.
> Support for default system proxy settings

- src/qml/PlayerView.qml
Fixes the problem with https://github.com/alamminsalo/orion/issues/65 -- openSUSE Tumbleweed only has QtQuick.Controls 2.0
> reduce QTQuick.Controls dependency to 2.0 for qt 5.7 compatibility

- src/model/ircchat.cpp
Currently, user supplied text is being put straight into an html text value of a Text control in rich text mode; that isn't terrible, because the HTML subset supported by the control is very limited to contain this sort of problem, but it isn't great.
> html escape chat content to be displayed in an html rich text field

- src/model/channelmanager.cpp
When a batch of followed channels arrives, check only that batch of channels for streams, not all the batches of followed channels that have arrived so far.
The multiple updates arriving because of this appears to be the underlying cause of what I was seeing in https://github.com/alamminsalo/orion/issues/73
> Eliminate unneeded extra stream checks

- README.md
- src/model/channelmanager.cpp
- src/model/channelmanager.h
- src/model/ircchat.cpp
- src/model/ircchat.h
- src/network/networkmanager.cpp
- src/network/networkmanager.h
- src/qml/IconButton.qml
- src/qml/PlayerView.qml
- src/qml/components/ComboBox.qml
- src/qml/components/GridPicker.qml
- src/qml/irc/Chat.qml
- src/qml/irc/ChatMessage.qml
- src/qml/irc/ChatView.qml
- src/util/jsonparser.cpp
- src/util/jsonparser.h
I could go on improving this forever probably but I might as well get a PR going for the work so far.
This adds:
- Display of Twitch emotes in chat, in sent and received messages
- Emote picker w/ search and keyboard controls
- Display users' Twitch badges from both APIs
- Tooltips for emotes & badges
- Add USERNOTICE support,
- Display channel notices closer to the look of the Twitch web-based chat
Kudos to @mroNNorm for the initial emote work, putting together the skeleton of the emote downloads & Flow/Repeater-based chat UI.
This should address https://github.com/alamminsalo/orion/issues/10 & https://github.com/alamminsalo/orion/issues/77 & https://github.com/alamminsalo/orion/issues/68
> Twitch Emotes & Badges Support

- src/qml/FavouritesView.qml
- src/qml/FeaturedView.qml
- src/qml/GamesView.qml
- src/qml/PlayerView.qml
- src/qml/SearchView.qml
- src/qml/components/ChannelGrid.qml
- src/qml/components/CommonGrid.qml
- src/qml/qml.qrc
This started out as something to facilitate chat testing for the emote support work but it seems like it could be useful for regular users as well
- Renamed the previous ChannelGrid to CommonGrid and refactored common channel views' (FavouritesView, FeaturedView, SearchView) grid components into a new ChannelGrid layer
- Added "Open Chat" command to ChannelGrid's context menu; it goes to player view and opens channel chat without starting playback
- **Made a normal click on an offline channel in a channel view also open chat**
> Add a way to open chat for offline channels; channel views refactoring

- src/qml/GamesView.qml
- src/qml/VodsView.qml
- src/qml/components/ChannelGrid.qml
- src/qml/components/CommonGrid.qml
- src/qml/components/VodGrid.qml
- src/qml/qml.qrc
Various changes to grids to support touch screen use (tested with a Windows 10 tablet)
- Fixed grids (e.g. channels, games, vods) click handlers to determine the clicked item with click coordinates as `selectedItem` does not get set when click signals fire due to touch events.
- Added press and hold handler to open context menu; increased the tooltip timeout slightly and added a tooltip timer reset on press so tooltips don't get ahead of the press and hold.
- Refactored `VodView` to use `ChannelGrid` rather than its own `VodGrid` and refactored tooltip implementations to support this. (Tooltips still require a mouse.)
> Make grids usable from touch screen 

- orion.pro
- src/model/channelmanager.cpp
- src/model/channelmanager.h
- src/model/imageprovider.cpp
- src/model/imageprovider.h
- src/model/ircchat.cpp
- src/model/ircchat.h
- src/qml/irc/Chat.qml
- src/qml/irc/ChatView.qml
- Refactor image download and `QQuickImageProvider` (from emotes implementation) out to the `ImageProvider`
- Use `ImageProvider` for badges also, so we preload badge images and buffer chat until loaded (gets rid of the layout jitter due to the current badges URLs used directly in QML)
- Switch to downloading to use `QSaveFile` (writing to a temp file that gets renamed once complete)
> Badges image provider

- src/player/mpvobject.cpp
The mpv backend does not enable hardware acceleration , even when the OS supports it (at least on Linux+Intel). This fixes it.
> [mpv] Enable hardware decoding if available

- src/qml/irc/ChatMessage.qml
At risk of pushing a layout nitpick, the lack of space between chat and the video bugs me (especially now  that there are rectangular badges at the left side of chat that are completely flush with the video)
> side margins for chat

- src/model/channelmanager.cpp
- src/model/channelmanager.h
- src/model/ircchat.cpp
- src/model/ircchat.h
- src/network/networkmanager.cpp
- src/network/networkmanager.h
- src/network/replaychat.h
- src/network/urls.h
- src/qml/PlayerView.qml
- src/qml/irc/Chat.qml
- src/qml/irc/ChatView.qml
- src/util/jsonparser.cpp
- src/util/jsonparser.h
When playing a VOD, replay chat that happened during the original broadcast instead of joining the live chat channel.
This is a hack, in that it uses the undocumented chat replay API that Twitch web UI uses, and it scrapes the VOD's chat replay start time from an error message (it seems that the chat-replay chunk requests need to be aligned to 30s intervals based on that start time to not miss messages, and the chat replay start value doesn't correspond to the VOD start time and doesn't seem to be available elsewhere).  Messages are deduplicated by id in a 150-300 second window in case the responses overlap, although since I switched to the start-aligned 30s intervals I don't see duplicates in practice.
FYI this branch contains the `mpv_time_offset_workaround` branch.
> VOD chat replay

- src/qml/PlayerView.qml
These must have been missed when `loadAndPlay` was reworked earlier.
Fixed
- reload stream button
- resume when network comes back
- resume when channel goes online
> load and play fixes

- src/model/ircchat.cpp
`QDateTime::fromSecsSinceEpoch` -> `QDateTime::fromMSecsSinceEpoch`
> Switch QDateTime static members for compatibility with older Qt

- src/model/ircchat.cpp
- src/model/ircchat.h
- src/qml/irc/Chat.qml
If we are in a channel, and there is a network issue and it recovers, don't join the live chat channel if there is a VOD chat replay in progress.
Occasionally while watching a VOD, I've seen a transient network error followed by chat switching back to the live chat channel. I haven't reproduced one of these in a debugger, but I've tested this fix by completely interrupting and restoring network connectivity.
> don't join live chat when the network recovers from an issue during chat replay

- src/model/ircchat.cpp
- src/model/ircchat.h
- src/qml/irc/Chat.qml
- src/qml/irc/ChatMessage.qml
- src/qml/irc/ChatView.qml
This adds support for receiving and sending (with `/msg`) private messages (whispers) from chat view.
Re https://github.com/alamminsalo/orion/issues/108. No notification support for whispers yet.
> receive and send whispers from the chat view

- src/model/channelmanager.cpp
- src/model/imageprovider.cpp
- src/model/imageprovider.h
- src/model/ircchat.cpp
- src/model/ircchat.h
- src/qml/irc/Chat.qml
- src/qml/irc/ChatView.qml
Adds some timer delays in the bulk emote download when the emote picker is first opened, to reduce the impact on the currently playing video and allow chat emote downloads to happen concurrently.
I also disabled a bunch of the debug output about badges.
> Bulk emote download performance tweaks

- src/qml/irc/ChatView.qml
Fix for https://github.com/rakslice/orion/issues/4 ; I'm not sure if this is a 100% fix, but I'm not able to reproduce the problem after this change
> Focus the emote search box immediately after emote picker is opened

- src/network/networkmanager.cpp
- src/network/urls.h
- src/qml/irc/Chat.qml
The request `NetworkManager::testConnection()` was doing is not present in the v5 API and results in an error; as a quick fix I changed it to do a different request that succeeds when the network is up. I also removed an unused incorrectly-typed QML signal handler.
> Double join chat quick fix

- src/model/channel.cpp
- src/model/channel.h
- src/model/channellistmodel.cpp
- src/network/networkmanager.cpp
- src/network/networkmanager.h
- src/qml/PlayerView.qml
- src/util/jsonparser.cpp
- src/util/jsonparser.h
Since the v5 API change, channels in the followed view continue to show as online after they have gone offline.
I found that it was up to code in `JsonParser` to determine which channels had gone offline, and to do this it required the current URL from `_links` collection in the response, which is no longer present in v5.
- Reworked response handling that depended on "_links" collections that are gone in v5
- Refactored things in `JsonParser` that depend on request URL up to `NetworkManager`
- Changed channel matching in `ChannelListModel::updateStream` to use ids
- Removed unused Channel constructors
> More fixes for the Twitch API v5 changes

- src/qml/MultimediaBackend.qml
While doing one more test with the the Multimedia backend, I thought I might to find some work around for the issue of VODs restarting at the beginning on reload.  The problem wasn't what I expected.
> fix VOD reload going back to the beginning with Qt Multimedia backend

- src/model/channelmanager.cpp
- src/model/channelmanager.h
- src/model/ircchat.cpp
- src/model/ircchat.h
- src/network/networkmanager.cpp
- src/network/networkmanager.h
- src/qml/OptionsView.qml
- src/util/jsonparser.cpp
- src/util/jsonparser.h
- Load the current Twitch user's blocked users list on login
- Don't display messages from blocked users
- Don't display whispers from blocked users
- Support chat commands `/block {username}` and `/unblock {username}` to block and unblock users
There doesn't seem to be a way to get notified when a user is blocked or unblocked by issuing a command in another chat session; you need to reload to get updated blocks. The Twitch web UI also has this problem.
> Chat user blocks support

- src/main.cpp
- src/model/channelmanager.cpp
- src/model/imageprovider.cpp
- src/model/ircchat.cpp
- src/model/vodmanager.cpp
- src/network/httpserver.h
- src/network/networkmanager.cpp
- src/notification/notificationmanager.cpp
- src/notification/notificationsender.cpp
- src/power/power.cpp
- src/systray.cpp
- src/util/runguard.cpp
Change `QObject::connect()` calls over to the function-pointer style introduced in Qt 5. https://doc.qt.io/qt-5/qobject.html#connect-3
In particular, this provides compile-time checking of parameter lists, avoiding situations where a function signature changes and a `connect()` call still builds but fails at runtime.
More backround: https://woboq.com/blog/new-signals-slots-syntax-in-qt5.html
> Switch to function-pointer-style QObject::connect()

- src/qml/irc/ChatView.qml
Fixes viewer list icon was showing up in the small mode view.
I made this change before but it probably got lost in move of the chat controls.
> hide chat controls in small mode

- src/model/channelmanager.cpp
- src/model/channelmanager.h
- src/network/networkmanager.cpp
- src/network/networkmanager.h
- src/qml/SearchView.qml
- src/util/jsonparser.cpp
- src/util/jsonparser.h
- Collect `_total` values from responses to be shown in search view
- Don't do another request if the total from the response that triggered the request check indicates no more items are available.
This avoids the search view indefinitely cascading responses to requests, while still allowing the user to cause another request by doing any other action that causes a request check (e.g. dragging past the end)
Fixes https://github.com/alamminsalo/orion/issues/170.
> search request loop fix

- src/model/channelmanager.cpp
- src/model/channelmanager.h
- src/model/imageprovider.cpp
- src/model/imageprovider.h
- src/model/ircchat.cpp
- src/model/ircchat.h
- src/network/networkmanager.cpp
- src/network/networkmanager.h
- src/network/urls.h
- src/qml/irc/Chat.qml
- src/qml/irc/ChatView.qml
- src/util/jsonparser.cpp
- src/util/jsonparser.h
- Display BTTV emote images in sent and received messages, including global emotes and channel-specific emotes when in the relevant channel
- Load BTTV emotes in the emote picker, including channel specific emotes if any
- Remove channel specific emotes from the picker when the current channel changes
Re request https://github.com/alamminsalo/orion/issues/140
> BTTV Emote Support

- src/model/ircchat.cpp
- src/model/ircchat.h
In the interest of showing a more consistent number of previous messages when seeking on moderately busy and very busy chats:
- request chat replay chunks covering the previous 90 seconds
- limit the number of previous messages shown to 15
> request more chat history when seeking and limit number of historical messages displayed

- src/main.cpp
- Added `-d` / `--debug` command line option that enables debug output in release builds.
- Enabled other standard options (help, version)
Note that this doesn't change the nature of debug output when it is enabled (so for instance as the Windows build is not a console-mode executable, you need DebugView or other debug-enabled IDE to see its debug output)
Also, debug output remains always-enabled in debug builds.
> Debug command line option

- src/model/channelmanager.cpp
- src/model/channelmanager.h
- src/qml/PlayerView.qml
- src/qml/VodsView.qml
- src/qml/components/Video.qml
- src/qml/irc/Chat.qml
- src/qml/irc/ChatView.qml
Track last playback positions of VODs, and save them in the local settings. When playing a VOD, default to the saved position if there is one, but allow starting at the beginning through the context menu.  Implements https://github.com/alamminsalo/orion/issues/121.
> VOD resume at last playback position

- appveyor.yml
- resources/orion-installer.iss
- Add Inno Setup installer build to AppVeyor
- Set installer version based on built orion.exe file version
- Put git commit ID in built snapshot and installer filenames
Re: https://github.com/alamminsalo/orion/issues/180
> Build Windows installer on AppVeyor

- src/qml/components/ChannelGrid.qml
Provides a way to open the stream for a channel when it is online but the API hasn't updated yet and is still indicating the channel is offline. Fixes https://github.com/alamminsalo/orion/issues/173.
> Provide "Watch live" menu item even when channel is offline

- README.md
- orion.pro
You may not want to merge this, but this is what I did to get Orion building on the ol' Apple. This may be relevant to #180.
I'm not really familiar with make or anything like that. Not sure if there is a better way than hard-coding the `mpv` version, but it was originally like that so I just updated it for what is currently on brew.
> What I needed to do to build on MacOS

- .travis.yml
- distfiles/deploy_mac.sh
- distfiles/fixlibs.sh
Here's a Travis build config for Mac, and `deploy_mac.sh`/`fixlibs.sh` changes to go along with it.  Since Travis doesn't have its own artifact archiving, I've included `deploy` sections in `.travis.yml` for Amazon S3 and GitHub Releases (tags only), which you supply with credentials using Travis environment var settings.
Inline comments in `.travis.yml` explain what is necessary to set up on the GitHub and AWS sides.
This takes whatever most recent Qt 5.9 build is in homebrew.
This does a build that uses Qt Multimedia.
Both of these `deploy` sections have `all_branches` set for testing, but you can remove that to default to `master` only, or set other specific branch with `branch:` (see https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A)
It seems like …
> Travis Mac build config

- appveyor.yml
- resources/orion-installer.iss
Windows Inno Setup installer script improvements
- For the 64-bit version, require 64-bit and use 64-bit mode so that Orion is installed to `\Program Files` rather than `\Program Files (x86)`
- Run the Visual C++ redistributable installer selected by `windeployqt`
- Include and run an additional Visual C++ redistributable installer if specified
In AppVeyor builds, specify the Visual Studio 2013 (12.0) redistributable installer also as the provided OpenSSL libs require it.
> win installer improvements

- src/qml/components/EmotePicker.qml
- src/qml/irc/ChatView.qml
- hook up `onShortcutOverride` to re-enable <kbd>Esc</kbd>
- use `forceActiveFocus()` for focus instead of setting `.focus`
> emote picker keyboard fixes

- src/qml/components/AppTray.qml
Currently on orion startup besides orion main window an orion tray menu is shown in top left corner of screen while I think it should not. At least it shows up for me in linux/x11/kde5/qt-5.9.2. This small patch disables showing the tray menu on startup.
> Don't show tray menu on startup.

- appveyor.yml
- resources/orion-installer.iss
Fix the appveyor build and use QtAV as backend. 
QtAV seems to have the best performance of the three backends and doesn't require external codecs, a switch for hardware-acceleration can be added later.
Using Qt 5.10 instead of the current 5.11.2 because of a freeze/deadlock when exiting after watching a stream, see [https://bugreports.qt.io/browse/QTBUG-61822](https://bugreports.qt.io/browse/QTBUG-61822?focusedCommentId=423760&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-423760)
Appveyor build and release artifacts can be found here: https://ci.appveyor.com/project/mrgreywater97397/orion
Should fix #204 and #231
> fix appveyor

- src/main.cpp
- src/model/channellistmodel.cpp
- src/model/gamelistmodel.cpp
- src/model/settingsmanager.cpp
- src/model/settingsmanager.h
- src/model/vodlistmodel.cpp
- src/player/mpvobject.cpp
- src/qml/MpvBackend.qml
- src/qml/MultimediaBackend.qml
- src/qml/OptionsView.qml
- src/qml/PlayerView.qml
- src/qml/QtAVBackend.qml
- src/qml/components/IconButtonFlat.qml
- src/qml/components/OptionCombo.qml
- src/qml/irc/ChatView.qml
Adds the option to change the decoder of the video to the QtAV and mpv backend.
On my test machine with windows 10 and a Intel i5 3570k and a AMD graphics card the performance differences are quite drastic for a normal 1080p stream:
Cpu Usage:
qtmultimedia: 25%
mpv (dxva_copy): 10%
mpv (no): 25%
QtAV (DXVA zero-copy): 3%
QtAV (FFmpeg): 8% 
Artifacts: https://ci.appveyor.com/project/mrgreywater/orion
This commit also gives an option to start multiple instances, fixes some gui issues and reorders the player controls to a more similar order as youtube etc. I can potentially split those up into more commits or PRs as necessary.
edit: there are still some issues, will push a fix for some things soon
> add hardware decoding options

- appveyor.yml
- ci/build_mpv.bat
- ci/build_openssl.bat
- ci/build_qtav.bat
This PR adds two builds to appveyor (mpv and qtmultimedia). Also compiles openssl now, since before the dlls were linked against the visual runtime 2013, which was included not in the installer.
All the dependencies are cached, and only recompiled if their batch file is changed.
appveyor: https://ci.appveyor.com/project/mrgreywater/orion
Would be nice to have a github release after this, since the last windows release on github that works for me was 1.6.0 beta.
> appveyor more builds, fix redist

- src/main.cpp
By default orion renders at this size:
This patch fixes the interface scaling on HiDPI displays:
Setting `QT_AUTO_SCREEN_SCALE_FACTOR=1` will render the interface back to its original scaling size. I personally run orion with `env QT_SCALE_FACTOR=1.25 orion`
Thanks for this software!
> Fix HiDPI using QT_AUTO_SCREEN_SCALE_FACTOR

- src/qml/irc/ViewerList.qml
The "Broadcaster" and "VIPs" sections were missing from the chat users list view so users in those categories were hidden in the users list.
I've added those categories in the usual positions they have in the Twitch web version's user lists. Also I've added some logic so that future new categories will at least be shown, in a consistent order, pending code changes to adjust the order to match whatever Twitch normally uses.
> add broadcaster, vips chat users list sections; add unrecognized sections automatically

- src/qml/irc/ChatView.qml
A quick workaround for not being able to send chat messages when the frontend's emotes have failed to initialize for whatever reason
> chat emotes not initializing workaround

- src/qml/PlayerView.qml
Addresses the spinning forever when there is no stream for the selected quality mentioned in #292 
- if the selected stream or VOD doesn't have the quality from the settings (e.g. the last quality manually set with the dropdown), try "source" instead
- if for whatever reason we still get a null URL, don't try playing the null UR, and log an error
> avoid just spinning forever when selected quality doesn't exist
