alamminsalo/orion

src/main.cpp
src/qml/PlayerView.qml
src/qml/irc/ChatMessage.qml
src/qml/irc/ChatView.qml

Added posibility to control volume level by mouse wheel.
Colorized nick names in chat
Disabled any console output in release build

Small simple features

---

src/model/channelmanager.cpp
src/model/channelmanager.h
src/notification/notificationsender.mm
src/qml/PlayerView.qml
src/qml/main.qml

Switched to QSettings instead of json file. FIxed issue with headers which stop building on mac sierra.

Small fixes

---

src/qml/PlayerView.qml
src/qml/Views.qml

I've seen this on the twitch website and their app and wanted it for this as well.

keep player visible if playing a stream while not being a selected view.

---

orion.pro

Some fixes for the Windows library code:
- fix for paths with spaces
- fix for debug build

Windows build fixes

---

src/model/ircchat.cpp
src/model/ircchat.h
src/qml/irc/Chat.qml
src/qml/irc/ChatView.qml

Fixes https://github.com/alamminsalo/orion/issues/58

use nickname from display-name tag if present

---

src/model/channelmanager.cpp

Fixes https://github.com/alamminsalo/orion/issues/62

Fix for streams requests not going out for the final chunk of followed channels

---

.gitignore
src/model/channelmanager.cpp

when the notifications option is disabled, don't show notifications :)

fix for a bunch of notifications showing up on launch even when notifications are turned off

---

src/qml/irc/ChatMessage.qml

Fixes https://github.com/alamminsalo/orion/issues/61.

display irc action correctly

---

src/qml/WebView.qml

Provide a value for accept-language for auth webview, based on the system locale, so we get the version of the Twitch login page in the user's language, if available.
Fixes https://github.com/alamminsalo/orion/issues/79

Login page random language fix

---

src/model/ircchat.cpp

Fixes https://github.com/alamminsalo/orion/issues/83

qt 5.6 build fix

---

appveyor.yml

This is a build job configuration for Appveyor, a Windows CI service analogous to Travis CI. You can set up builds for open source projects' public repositories without subscribing to a paid service.

Appveyor configuration

---

src/model/ircchat.cpp

Fixes https://github.com/alamminsalo/orion/issues/86.
There wasn't an obvious baked-in solution in for this in QString, so I added true unicode character counter and hooked it up in the emoji splitting

unicode surrogate pairs emoji positioning fix

---

src/model/ircchat.cpp
src/model/ircchat.h

Fixes https://github.com/alamminsalo/orion/issues/91

Filter wrong channel chat

---

src/qml/MpvBackend.qml

Workaround for https://github.com/alamminsalo/orion/issues/110

workaround offset in the mpv backend positions

---

src/model/channelmanager.cpp
src/model/channelmanager.h
src/model/ircchat.cpp
src/model/ircchat.h
src/network/networkmanager.cpp
src/network/networkmanager.h
src/qml/PlayerView.qml
src/qml/irc/Chat.qml
src/qml/irc/ChatView.qml

Fix for issues previous where previous VOD chat replay activity continues after switching out of VOD chat replay or switching to a different VOD

fix VOD chat replay cleanup issues

---

appveyor.yml

Switch appveyor config to use lachs0r's libmpv builds (the ones from mpv.srsfckn.biz)

Appveyor switch libmpv build

---

src/customapp.cpp
src/customapp.h
src/model/channel.cpp
src/model/channel.h
src/model/channellistmodel.cpp
src/model/channelmanager.cpp
src/model/channelmanager.h
src/model/gamelistmodel.cpp
src/model/imageprovider.cpp
src/model/imageprovider.h
src/model/ircchat.cpp
src/model/ircchat.h
src/model/vodlistmodel.cpp
src/network/httpserver.h
src/network/networkmanager.cpp
src/network/networkmanager.h
src/util/jsonparser.cpp

This was partly in response to https://github.com/alamminsalo/orion/issues/107

Assorted fixes for warnings and KDE/clazy level 0-1 issues

---

src/model/channelmanager.cpp
src/model/channelmanager.h
src/network/networkmanager.cpp
src/network/networkmanager.h
src/network/urls.h
src/qml/PlayerView.qml
src/qml/fonts/fontAwesome.js
src/qml/irc/ChatView.qml
src/util/jsonparser.cpp
src/util/jsonparser.h

Added a viewer list in the chat view area, toggled by the button in the player view top nav bar

Viewer List

---

src/qml/PlayerView.qml
src/qml/irc/ChatView.qml

- Fix mini-player / `smallMode` issues with swapped chat (https://github.com/alamminsalo/orion/issues/129)
- Fix chat controls toolbar position with swapped chat

Swapped chat fixes

---

src/qml/irc/ChatView.qml

set a minimum brightness of the random username colours

---

src/model/channelmanager.cpp
src/model/channelmanager.h
src/model/vodmanager.cpp
src/model/vodmanager.h
src/network/networkmanager.cpp
src/network/networkmanager.h
src/qml/PlayerView.qml
src/qml/VodsView.qml
src/qml/irc/Chat.qml
src/qml/irc/ChatView.qml
src/util/jsonparser.cpp
src/util/jsonparser.h

- Updated all the kraken API calls to use v5 https://github.com/alamminsalo/orion/issues/76
- Fixed some search strings going into the URL unescaped

Move to Twitch API v5; fixed search escaping

---

src/model/channelmanager.cpp

Fixes https://github.com/alamminsalo/orion/issues/151.

Local favourites fixes

---

src/qml/MpvBackend.qml
src/qml/PlayerView.qml

Re https://github.com/alamminsalo/orion/issues/150

set audio client name and title in libmpv

---

src/model/channelmanager.cpp
src/model/channelmanager.h
src/network/networkmanager.cpp
src/network/networkmanager.h
src/util/jsonparser.cpp
src/util/jsonparser.h

Fixes https://github.com/alamminsalo/orion/issues/165 .

Switch followed and blocked paged results loading to use JSON _total

---

src/util/jsonparser.cpp

Fixes https://github.com/alamminsalo/orion/issues/174.

Explicitly percent-encode HLS token

---

src/util/jsonparser.cpp
src/util/jsonparser.h

Fixes use of high DPI bits images

use SettingsManager::hiDpi() for bits images also

---

src/qml/irc/ChatView.qml

Fix for https://github.com/alamminsalo/orion/issues/199

leave chat input focused after sending a message

---

src/model/ircchat.cpp
src/model/ircchat.h
src/model/vodmanager.cpp
src/model/vodmanager.h
src/network/networkmanager.cpp
src/network/networkmanager.h
src/network/replaychat.h
src/network/urls.h
src/util/jsonparser.cpp
src/util/jsonparser.h

Fixes https://github.com/alamminsalo/orion/issues/209.

first cut of new chat replay

---

src/main.cpp
src/model/ircchat.cpp
src/model/ircchat.h

this notifys the user if someone was banned or timed out from chat, how long they were timed out and the reason if one was given. 
also fixed some build warnings.

Clear Chat

---

appveyor.yml

Bump the Qt version in the Appveyor config to 5.9.3 Re #180

bump appveyor qt ver

---

src/network/httpserver.cpp

Fix HTTP response socket output

---

src/network/networkmanager.cpp
src/network/networkmanager.h
src/network/urls.h

fix for #283 
https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851

get streams using twitch api key
